Init commi
stuvusIT/ansible_syncrify_server pull request #1
Opened 2019-08-30 20:03 UTC by Scriptkiddi

2019-09-01 11:12 UTC, dasJ requested changes

2019-09-01 11:12 UTC, dasJ commented on README.md
> +# Syncrify-Server
Commit message…

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_admin_email`                     | :heavy_check_mark:                          |                                              |
So we don't do descriptions anymore?

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_smtp_security`                   | `None`                                      | TLS/SSL/None                                 |
This is not a description

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_smtp_port`                       | `587`                                       | Smtp port                                    |
It's called SMTP. Also, what is it for? This not a description either

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_smtp_server`                     | `null`                                      | Url of the smtp server                       |
Yes but what for

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_use_web_smtp`                    | `false`                                     | Enable web smtp                              |
So… SMTP over HTTP? Or what?

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_email_server_web_service_host`   | `null`                                      | Web email service host url                   |
Excuse me?

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_use_rdbms_for_delete_retension`  | `true`                                      | Enable or disable rdbms retension            |
Pretty sure you mean retention. Retension is something different

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_http_port_ssl`                   | `-1`                                        | SSL Port -1 disables the port                |
```suggestion
| `syncrify_server_http_port_ssl`                   | `-1`                                        | SSL Port. A value of `-1` disables the port                |
```

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_last_selected_tab`               | `1`                                         | Which tab was last selected                  |
```suggestion
| `syncrify_server_last_selected_tab`               | `1`                                         | Tab which was last selected                  |
```

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_last_selected_tab`               | `1`                                         | Which tab was last selected                  |
Also. What?

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_cd`                              | `1565091689911`                             |                                              |
????

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_nt_service_command`              | `systemctl start syncrify.service`          | The nt service command                       |
Okay.

2019-09-01 11:12 UTC, dasJ commented on README.md
> +| `syncrify_server_mimic_html_files`                | `false`                                     | Mimic html files                             |
Pretty sure it's called HTML

2019-09-01 11:12 UTC, dasJ commented on README.md
> +          root /opt/Syncrify/htdocs/webapps/ROOT;
Maybe mention this path at the top of the readme

2019-09-01 11:12 UTC, dasJ commented on README.md
> +          proxy_pass http://backend;
Why use an upstream in the first place when only one host is specified?

2019-09-01 11:12 UTC, dasJ commented on meta/main.yml
> +  author: Insert author(s) here
Did you even try

2019-09-01 11:12 UTC, dasJ commented on tasks/main.yml
> +    name: openjdk-11-jre
Why not default to the JRE you install here?

2019-09-01 11:12 UTC, dasJ commented on tasks/main.yml
> +    dest: /tmp/syncrify-server.tar
Forgot about global_cache_dir?

2019-09-01 11:12 UTC, dasJ commented on tasks/main.yml
> +  when: syncrify_folder.stat.exists
Why?

2019-09-01 11:12 UTC, dasJ commented on tasks/main.yml
> +- name: Set executable for Install.sh
```suggestion
- name: Set executable bit for Install.sh
```

2019-09-01 11:12 UTC, dasJ commented on tasks/main.yml
> +    dest: /opt/Syncrify/config/AppConfig.xml
So no permission stuff?

2019-09-01 11:12 UTC, dasJ commented on tasks/main.yml
> +- name: Systemd service
That's not a really helpful name

2019-09-01 11:12 UTC, dasJ commented on templates/syncrify.service.j2
> +ExecStart=/etc/init.d/syncrify start
Is there *any* reason to run this as root?

2019-09-07 16:34 UTC, Scriptkiddi commented
@dasJ please review

2019-09-28 20:05 UTC, Scriptkiddi commented
@dasJ

2019-10-06 16:06 UTC, dasJ commented
Automatically bumping this issue because it was inactive for 7 days.

2019-10-07 11:42 UTC, Scriptkiddi commented
@dasJ Automatically bumping this issue because it was inactive for 7 days. ja meinsch

2020-01-05 01:17 UTC, closed without merging